### PR TITLE
Hover CSS is taking precedence over focus  #58

### PR DESCRIPTION
**Pull request by solsticesurfer**
Fix to ensure the focus effect takes precedence over the hover effect.

### CODE REVIEW

**Comment by devinhalladay** [comment]
Small world, I was just about to submit a PR for this same issue :) You should make the same change in the Sass file, but if you're not familiar with Sass let me know and I can do and submit another PR.

**Comment by kumailht** [comment]
@devinhalladay is spot on. The CSS file is generated from source written in this SASS file:
https://github.com/kumailht/gridforms/blob/master/gridforms/gridforms.sass

**Comment by solsticesurfer** [comment]
Shame on me for overlooking that. Pushed the SASS change.

**Comment by kumailht** [comment]
@solsticesurfer Thank you for your contribution to GridForms!

**Pull request merged**
